theme: jekyll-theme-cayman

title: unipr-org
description: L'organizzazione Github dedicata a riunire tutti gli studenti di Informatica dell'Universit√† di Parma.

show_downloads: true
google_analytics:
exclude:

